[project]
name = "bmi-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
]

[dependency-groups]
dev = [
    "streamlit>=1.43.2",
]
